name: Publish Nest.land

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.4.6
      - run: deno install -Af --unstable https://x.nest.land/eggs@0.3.1/eggs.ts
        
      - name: Publish module
        run: |
          export PATH="/home/runner/.deno/bin:$PATH"
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish --yes
          
